# Generated by Django 4.1.5 on 2023-02-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="User",
            new_name="user",
        ),
    ]
