# Generated by Django 4.1.5 on 2023-02-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_user_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="coupon",
        ),
    ]
