# Generated by Django 4.1.5 on 2023-01-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_colorvariant_sizevariant_product_color_variant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sizevariant",
            old_name="color_name",
            new_name="size_name",
        ),
    ]
